"""job_criteria_and_application_notes

Revision ID: 6875eab5dcc5
Revises: d1def644e25b
Create Date: 2026-08-06 19:20:05.949526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6875eab5dcc5'
down_revision: Union[str, Sequence[str], None] = 'd1def644e25b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # `employment_type` từng là input text tự do ở JobForm.tsx (chưa từng bị
    # kiểm soát) — dọn mọi giá trị không khớp enum mới trước khi ALTER, tránh
    # `USING` cast fail cứng nếu có ai đã gõ tay giá trị khác 'official'/'seasonal'.
    op.execute(
        "UPDATE jobs SET employment_type = NULL "
        "WHERE employment_type IS NOT NULL "
        "AND employment_type NOT IN ('official', 'seasonal')"
    )

    employment_type_enum = sa.Enum('official', 'seasonal', name='employment_type')
    salary_period_enum = sa.Enum('weekly', 'monthly', name='salary_period')
    employment_type_enum.create(op.get_bind(), checkfirst=True)
    salary_period_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('salary_period', salary_period_enum, nullable=True))
    op.alter_column(
        'jobs', 'employment_type',
        existing_type=sa.VARCHAR(length=50),
        type_=employment_type_enum,
        existing_nullable=True,
        postgresql_using='employment_type::employment_type',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'jobs', 'employment_type',
        existing_type=sa.Enum('official', 'seasonal', name='employment_type'),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
        postgresql_using='employment_type::text',
    )
    op.drop_column('jobs', 'salary_period')
    op.drop_column('applications', 'notes')
    # ### end Alembic commands ###

    # --- Thủ công: autogenerate không tự sinh DROP TYPE cho Postgres ENUM khi
    # downgrade — phải xoá tay, đặt sau khi mọi cột dùng các type này đã bị
    # drop/đổi kiểu ở trên (xem mẫu ở 7dcb960fdfb3). ---
    sa.Enum(name="employment_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="salary_period").drop(op.get_bind(), checkfirst=True)
