/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Application */
        post: operations["create_application_api_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Lead
         * @description Lead tư vấn chung từ chatbot (không gắn 1 tin tuyển dụng cụ thể) — ghi vào
         *     cùng bảng `applications` với `job_id=NULL`, `source=CHATBOT` (hardcode server-side,
         *     KHÔNG nhận từ client). Tách riêng khỏi `POST /api/applications` vì đó là endpoint
         *     rủi ro cao nhất hệ thống (PII, đã có nhiều test bao phủ) — xem CLAUDE.md.
         *     Không bao giờ log body/field của endpoint này (SĐT là PII).
         */
        post: operations["create_lead_api_leads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recent Companies */
        get: operations["list_recent_companies_api_companies_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Posts */
        get: operations["list_posts_api_posts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Post */
        get: operations["get_post_api_posts__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/job-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Job Categories */
        get: operations["list_job_categories_api_job_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/industrial-parks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Industrial Parks */
        get: operations["list_industrial_parks_api_industrial_parks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs Admin */
        get: operations["list_jobs_admin_api_admin_jobs_get"];
        put?: never;
        /** Create Job Admin */
        post: operations["create_job_admin_api_admin_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Admin */
        get: operations["get_job_admin_api_admin_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Delete Job Admin */
        delete: operations["delete_job_admin_api_admin_jobs__job_id__delete"];
        options?: never;
        head?: never;
        /** Update Job Admin */
        patch: operations["update_job_admin_api_admin_jobs__job_id__patch"];
        trace?: never;
    };
    "/api/admin/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Posts Admin */
        get: operations["list_posts_admin_api_admin_posts_get"];
        put?: never;
        /** Create Post Admin */
        post: operations["create_post_admin_api_admin_posts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/posts/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Post Admin */
        get: operations["get_post_admin_api_admin_posts__post_id__get"];
        put?: never;
        post?: never;
        /** Delete Post Admin */
        delete: operations["delete_post_admin_api_admin_posts__post_id__delete"];
        options?: never;
        head?: never;
        /** Update Post Admin */
        patch: operations["update_post_admin_api_admin_posts__post_id__patch"];
        trace?: never;
    };
    "/api/admin/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Companies Admin */
        get: operations["list_companies_admin_api_admin_companies_get"];
        put?: never;
        /** Create Company Admin */
        post: operations["create_company_admin_api_admin_companies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/companies/{company_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Company Admin */
        get: operations["get_company_admin_api_admin_companies__company_id__get"];
        put?: never;
        post?: never;
        /** Delete Company Admin */
        delete: operations["delete_company_admin_api_admin_companies__company_id__delete"];
        options?: never;
        head?: never;
        /** Update Company Admin */
        patch: operations["update_company_admin_api_admin_companies__company_id__patch"];
        trace?: never;
    };
    "/api/admin/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Applications Admin */
        get: operations["list_applications_admin_api_admin_applications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/applications/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Applications Csv */
        get: operations["export_applications_csv_api_admin_applications_export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Application Admin */
        get: operations["get_application_admin_api_admin_applications__application_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Application Admin */
        patch: operations["update_application_admin_api_admin_applications__application_id__patch"];
        trace?: never;
    };
    "/api/admin/applications/{application_id}/cv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Application Cv */
        get: operations["download_application_cv_api_admin_applications__application_id__cv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/applications/{application_id}/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Purge Application
         * @description Xoá dữ liệu cá nhân theo yêu cầu của ứng viên (NĐ13/2023) — giữ lại
         *     `reference_code`/`job_id`/`status`/`created_at` để không phá vỡ thống kê tổng
         *     hợp (P7), chỉ xoá hẳn các trường định danh cá nhân + file CV trên đĩa.
         */
        post: operations["purge_application_api_admin_applications__application_id__purge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/stats/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Overview */
        get: operations["get_overview_api_admin_stats_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/stats/by-province": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get By Province */
        get: operations["get_by_province_api_admin_stats_by_province_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/stats/by-age-group": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get By Age Group */
        get: operations["get_by_age_group_api_admin_stats_by_age_group_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/stats/by-industrial-park": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get By Industrial Park */
        get: operations["get_by_industrial_park_api_admin_stats_by_industrial_park_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users Admin */
        get: operations["list_users_admin_api_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgeGroupStatOut */
        AgeGroupStatOut: {
            /** Bucket */
            bucket: string;
            /** Label */
            label: string;
            /** Count */
            count: number;
        };
        /** ApplicationAdminOut */
        ApplicationAdminOut: {
            /** Id */
            id: number;
            /** Reference Code */
            reference_code: string;
            /** Job Id */
            job_id: number | null;
            /** Job Slug */
            job_slug: string | null;
            /** Job Title */
            job_title: string | null;
            /** Full Name */
            full_name: string;
            /** Phone */
            phone: string;
            /** Email */
            email: string | null;
            /** Birth Date */
            birth_date: string | null;
            /** Age */
            age: number | null;
            /** Gender */
            gender: string | null;
            /** Province Code */
            province_code: string | null;
            /** Province Name */
            province_name: string | null;
            /** Hometown Text */
            hometown_text: string | null;
            /** Has Cv */
            has_cv: boolean;
            /** Cv Original Name */
            cv_original_name: string | null;
            /** Notes */
            notes: string | null;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /** Assigned To Id */
            assigned_to_id: number | null;
            /** Assigned To Email */
            assigned_to_email: string | null;
            /** Purged At */
            purged_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ApplicationAdminUpdate */
        ApplicationAdminUpdate: {
            status?: components["schemas"]["ApplicationStatus"] | null;
            /** Assigned To Id */
            assigned_to_id?: number | null;
        };
        /** ApplicationCreateResponse */
        ApplicationCreateResponse: {
            /** Ok */
            ok: boolean;
            /** Reference Code */
            reference_code: string;
            /**
             * Duplicate
             * @default false
             */
            duplicate: boolean;
            /** Message */
            message?: string | null;
        };
        /**
         * ApplicationSource
         * @enum {string}
         */
        ApplicationSource: "web" | "chatbot" | "zalo" | "facebook" | "walk_in";
        /**
         * ApplicationStatus
         * @enum {string}
         */
        ApplicationStatus: "new" | "contacted" | "interviewing" | "hired" | "rejected";
        /** Body_create_application_api_applications_post */
        Body_create_application_api_applications_post: {
            /** Full Name */
            full_name: string;
            /** Phone */
            phone: string;
            /** Email */
            email?: string | null;
            /** Birth Date */
            birth_date?: string | null;
            gender?: components["schemas"]["Gender"] | null;
            /** Province Code */
            province_code?: string | null;
            /** Hometown Text */
            hometown_text?: string | null;
            /** Job Slug */
            job_slug: string;
            /**
             * Consent Given
             * @default false
             */
            consent_given: boolean;
            /**
             * Website
             * @default
             */
            website: string;
            /** Form Rendered At */
            form_rendered_at: string;
            /** Cv */
            cv?: string | null;
        };
        /** Body_create_lead_api_leads_post */
        Body_create_lead_api_leads_post: {
            /** Phone */
            phone: string;
            /** Full Name */
            full_name?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Consent Given
             * @default false
             */
            consent_given: boolean;
            /**
             * Website
             * @default
             */
            website: string;
            /** Form Rendered At */
            form_rendered_at: string;
        };
        /** ChatMessageIn */
        ChatMessageIn: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /** History */
            history?: components["schemas"]["ChatMessageIn"][];
        };
        /** CompanyAdminCreate */
        CompanyAdminCreate: {
            /** Display Name Public */
            display_name_public?: string | null;
            /** Logo Initials */
            logo_initials?: string | null;
            /** Logo Url */
            logo_url?: string | null;
            /**
             * Is Partner
             * @default true
             */
            is_partner: boolean;
            /** Name */
            name: string;
        };
        /** CompanyAdminOut */
        CompanyAdminOut: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Display Name Public */
            display_name_public: string | null;
            /** Logo Initials */
            logo_initials: string | null;
            /** Logo Url */
            logo_url: string | null;
            /** Is Partner */
            is_partner: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CompanyAdminUpdate */
        CompanyAdminUpdate: {
            /** Name */
            name?: string | null;
            /** Display Name Public */
            display_name_public?: string | null;
            /** Logo Initials */
            logo_initials?: string | null;
            /** Logo Url */
            logo_url?: string | null;
            /** Is Partner */
            is_partner?: boolean | null;
        };
        /** CompanyPublic */
        CompanyPublic: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Logo Initials */
            logo_initials: string | null;
            /** Logo Url */
            logo_url: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * EmploymentType
         * @enum {string}
         */
        EmploymentType: "official" | "seasonal";
        /**
         * Gender
         * @enum {string}
         */
        Gender: "male" | "female" | "other";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IndustrialParkOut */
        IndustrialParkOut: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Province Code */
            province_code: string;
            /** District Name */
            district_name: string | null;
        };
        /** IndustrialParkPublic */
        IndustrialParkPublic: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
        };
        /** IndustrialParkStatOut */
        IndustrialParkStatOut: {
            /** Industrial Park Slug */
            industrial_park_slug: string | null;
            /** Industrial Park Name */
            industrial_park_name: string;
            /** Count */
            count: number;
        };
        /** JobAdminCreate */
        JobAdminCreate: {
            /** Salary Min */
            salary_min?: number | null;
            /** Salary Max */
            salary_max?: number | null;
            /**
             * Salary Negotiable
             * @default false
             */
            salary_negotiable: boolean;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
            /** Age Min */
            age_min?: number | null;
            /** Age Max */
            age_max?: number | null;
            /** Shift Type */
            shift_type?: string | null;
            employment_type?: components["schemas"]["EmploymentType"] | null;
            salary_period?: components["schemas"]["SalaryPeriod"] | null;
            /** Description */
            description?: string | null;
            /** Requirements */
            requirements?: string | null;
            /** Benefits */
            benefits?: string | null;
            /** Deadline */
            deadline?: string | null;
            /** @default draft */
            status: components["schemas"]["JobStatus"];
            /**
             * Is Hot
             * @default false
             */
            is_hot: boolean;
            /** Meta Title */
            meta_title?: string | null;
            /** Meta Description */
            meta_description?: string | null;
            /** Title */
            title: string;
            /** Company Slug */
            company_slug: string;
            /** Category Slug */
            category_slug: string;
            /** Industrial Park Slug */
            industrial_park_slug?: string | null;
            /** Province Code */
            province_code: string;
        };
        /** JobAdminOut */
        JobAdminOut: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Company Slug */
            company_slug: string;
            /** Company Name */
            company_name: string;
            /** Category Slug */
            category_slug: string;
            /** Category Name */
            category_name: string;
            /** Industrial Park Slug */
            industrial_park_slug: string | null;
            /** Industrial Park Name */
            industrial_park_name: string | null;
            /** Province Code */
            province_code: string;
            /** Province Name */
            province_name: string;
            /** Salary Min */
            salary_min: number | null;
            /** Salary Max */
            salary_max: number | null;
            /** Salary Negotiable */
            salary_negotiable: boolean;
            /** Quantity */
            quantity: number;
            /** Age Min */
            age_min: number | null;
            /** Age Max */
            age_max: number | null;
            /** Shift Type */
            shift_type: string | null;
            employment_type: components["schemas"]["EmploymentType"] | null;
            salary_period: components["schemas"]["SalaryPeriod"] | null;
            /** Description */
            description: string | null;
            /** Requirements */
            requirements: string | null;
            /** Benefits */
            benefits: string | null;
            /** Deadline */
            deadline: string | null;
            /** Status */
            status: string;
            /** Is Hot */
            is_hot: boolean;
            /** Published At */
            published_at: string | null;
            /** View Count */
            view_count: number;
            /** Meta Title */
            meta_title: string | null;
            /** Meta Description */
            meta_description: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** JobAdminUpdate */
        JobAdminUpdate: {
            /** Title */
            title?: string | null;
            /** Company Slug */
            company_slug?: string | null;
            /** Category Slug */
            category_slug?: string | null;
            /** Industrial Park Slug */
            industrial_park_slug?: string | null;
            /** Province Code */
            province_code?: string | null;
            /** Salary Min */
            salary_min?: number | null;
            /** Salary Max */
            salary_max?: number | null;
            /** Salary Negotiable */
            salary_negotiable?: boolean | null;
            /** Quantity */
            quantity?: number | null;
            /** Age Min */
            age_min?: number | null;
            /** Age Max */
            age_max?: number | null;
            /** Shift Type */
            shift_type?: string | null;
            employment_type?: components["schemas"]["EmploymentType"] | null;
            salary_period?: components["schemas"]["SalaryPeriod"] | null;
            /** Description */
            description?: string | null;
            /** Requirements */
            requirements?: string | null;
            /** Benefits */
            benefits?: string | null;
            /** Deadline */
            deadline?: string | null;
            status?: components["schemas"]["JobStatus"] | null;
            /** Is Hot */
            is_hot?: boolean | null;
            /** Meta Title */
            meta_title?: string | null;
            /** Meta Description */
            meta_description?: string | null;
        };
        /** JobCategoryPublic */
        JobCategoryPublic: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
        };
        /** JobCategoryWithCount */
        JobCategoryWithCount: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Job Count */
            job_count: number;
        };
        /** JobDetail */
        JobDetail: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            company: components["schemas"]["CompanyPublic"];
            category: components["schemas"]["JobCategoryPublic"];
            industrial_park: components["schemas"]["IndustrialParkPublic"] | null;
            /** Province Code */
            province_code: string;
            /** Province Name */
            province_name: string;
            /** Salary Min */
            salary_min: number | null;
            /** Salary Max */
            salary_max: number | null;
            /** Salary Negotiable */
            salary_negotiable: boolean;
            employment_type: components["schemas"]["EmploymentType"] | null;
            salary_period: components["schemas"]["SalaryPeriod"] | null;
            /** Is Hot */
            is_hot: boolean;
            /** Deadline */
            deadline: string | null;
            /** Published At */
            published_at: string | null;
            /** Quantity */
            quantity: number;
            /** Age Min */
            age_min: number | null;
            /** Age Max */
            age_max: number | null;
            /** Shift Type */
            shift_type: string | null;
            /** Description */
            description: string | null;
            /** Requirements */
            requirements: string | null;
            /** Benefits */
            benefits: string | null;
            /** Status */
            status: string;
            /** Meta Title */
            meta_title: string | null;
            /** Meta Description */
            meta_description: string | null;
        };
        /** JobListItem */
        JobListItem: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            company: components["schemas"]["CompanyPublic"];
            category: components["schemas"]["JobCategoryPublic"];
            industrial_park: components["schemas"]["IndustrialParkPublic"] | null;
            /** Province Code */
            province_code: string;
            /** Province Name */
            province_name: string;
            /** Salary Min */
            salary_min: number | null;
            /** Salary Max */
            salary_max: number | null;
            /** Salary Negotiable */
            salary_negotiable: boolean;
            employment_type: components["schemas"]["EmploymentType"] | null;
            salary_period: components["schemas"]["SalaryPeriod"] | null;
            /** Is Hot */
            is_hot: boolean;
            /** Deadline */
            deadline: string | null;
            /** Published At */
            published_at: string | null;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "draft" | "published" | "closed" | "archived";
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MeResponse */
        MeResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Role */
            role: string;
        };
        /** PageResponse[ApplicationAdminOut] */
        PageResponse_ApplicationAdminOut_: {
            /** Items */
            items: components["schemas"]["ApplicationAdminOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** PageResponse[CompanyAdminOut] */
        PageResponse_CompanyAdminOut_: {
            /** Items */
            items: components["schemas"]["CompanyAdminOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** PageResponse[JobAdminOut] */
        PageResponse_JobAdminOut_: {
            /** Items */
            items: components["schemas"]["JobAdminOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** PageResponse[JobListItem] */
        PageResponse_JobListItem_: {
            /** Items */
            items: components["schemas"]["JobListItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** PageResponse[PostAdminOut] */
        PageResponse_PostAdminOut_: {
            /** Items */
            items: components["schemas"]["PostAdminOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** PostAdminCreate */
        PostAdminCreate: {
            /** Excerpt */
            excerpt?: string | null;
            /** Content */
            content?: string | null;
            /** Cover Image Url */
            cover_image_url?: string | null;
            /** @default draft */
            status: components["schemas"]["PostStatus"];
            /** Meta Title */
            meta_title?: string | null;
            /** Meta Description */
            meta_description?: string | null;
            /** Title */
            title: string;
            type: components["schemas"]["PostType"];
        };
        /** PostAdminOut */
        PostAdminOut: {
            /** Id */
            id: number;
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Excerpt */
            excerpt: string | null;
            /** Content */
            content: string | null;
            /** Cover Image Url */
            cover_image_url: string | null;
            /** Type */
            type: string;
            /** Status */
            status: string;
            /** Published At */
            published_at: string | null;
            /** Meta Title */
            meta_title: string | null;
            /** Meta Description */
            meta_description: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PostAdminUpdate */
        PostAdminUpdate: {
            /** Title */
            title?: string | null;
            type?: components["schemas"]["PostType"] | null;
            /** Excerpt */
            excerpt?: string | null;
            /** Content */
            content?: string | null;
            /** Cover Image Url */
            cover_image_url?: string | null;
            status?: components["schemas"]["PostStatus"] | null;
            /** Meta Title */
            meta_title?: string | null;
            /** Meta Description */
            meta_description?: string | null;
        };
        /** PostDetail */
        PostDetail: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Excerpt */
            excerpt: string | null;
            /** Cover Image Url */
            cover_image_url: string | null;
            /** Type */
            type: string;
            /** Published At */
            published_at: string | null;
            /** Content */
            content: string | null;
            /** Meta Title */
            meta_title: string | null;
            /** Meta Description */
            meta_description: string | null;
        };
        /** PostListItem */
        PostListItem: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Excerpt */
            excerpt: string | null;
            /** Cover Image Url */
            cover_image_url: string | null;
            /** Type */
            type: string;
            /** Published At */
            published_at: string | null;
        };
        /**
         * PostStatus
         * @enum {string}
         */
        PostStatus: "draft" | "published" | "archived";
        /**
         * PostType
         * @enum {string}
         */
        PostType: "news" | "policy" | "guide" | "scam_alert" | "event";
        /** ProvinceStatOut */
        ProvinceStatOut: {
            /** Province Code */
            province_code: string | null;
            /** Province Name */
            province_name: string;
            /** Count */
            count: number;
        };
        /**
         * SalaryPeriod
         * @enum {string}
         */
        SalaryPeriod: "weekly" | "monthly";
        /** StatsOverviewOut */
        StatsOverviewOut: {
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            /** Granularity */
            granularity: string;
            /** Total */
            total: number;
            /** By Status */
            by_status: {
                [key: string]: number;
            };
            /** Series */
            series: components["schemas"]["StatsSeriesPoint"][];
        };
        /** StatsSeriesPoint */
        StatsSeriesPoint: {
            /** Period */
            period: string;
            /** Count */
            count: number;
        };
        /** UserAdminOut */
        UserAdminOut: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Role */
            role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_application_api_applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_application_api_applications_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_lead_api_leads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_create_lead_api_leads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recent_companies_api_companies_recent_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                q?: string | null;
                category?: string | null;
                industrial_park?: string | null;
                province?: string | null;
                salary_min?: number | null;
                employment_type?: components["schemas"]["EmploymentType"] | null;
                salary_period?: components["schemas"]["SalaryPeriod"] | null;
                page?: number;
                page_size?: number;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_JobListItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_posts_api_posts_get: {
        parameters: {
            query?: {
                type?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_post_api_posts__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_job_categories_api_job_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCategoryWithCount"][];
                };
            };
        };
    };
    list_industrial_parks_api_industrial_parks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndustrialParkOut"][];
                };
            };
        };
    };
    list_jobs_admin_api_admin_jobs_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["JobStatus"] | null;
                q?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_JobAdminOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_admin_api_admin_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobAdminCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_admin_api_admin_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_job_admin_api_admin_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_job_admin_api_admin_jobs__job_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobAdminUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_posts_admin_api_admin_posts_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["PostStatus"] | null;
                q?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_PostAdminOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_post_admin_api_admin_posts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostAdminCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_post_admin_api_admin_posts__post_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_post_admin_api_admin_posts__post_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_post_admin_api_admin_posts__post_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostAdminUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_companies_admin_api_admin_companies_get: {
        parameters: {
            query?: {
                q?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_CompanyAdminOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_company_admin_api_admin_companies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyAdminCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_company_admin_api_admin_companies__company_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_company_admin_api_admin_companies__company_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_company_admin_api_admin_companies__company_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                company_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyAdminUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_applications_admin_api_admin_applications_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ApplicationStatus"] | null;
                source?: components["schemas"]["ApplicationSource"] | null;
                job_id?: number | null;
                industrial_park_slug?: string | null;
                province_code?: string | null;
                assigned_to_id?: number | null;
                unassigned_only?: boolean;
                q?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_ApplicationAdminOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_applications_csv_api_admin_applications_export_csv_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ApplicationStatus"] | null;
                source?: components["schemas"]["ApplicationSource"] | null;
                job_id?: number | null;
                industrial_park_slug?: string | null;
                province_code?: string | null;
                assigned_to_id?: number | null;
                unassigned_only?: boolean;
                q?: string | null;
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_application_admin_api_admin_applications__application_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_application_admin_api_admin_applications__application_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationAdminUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_application_cv_api_admin_applications__application_id__cv_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    purge_application_api_admin_applications__application_id__purge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_overview_api_admin_stats_overview_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                granularity?: "day" | "week" | "month";
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOverviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_by_province_api_admin_stats_by_province_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvinceStatOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_by_age_group_api_admin_stats_by_age_group_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgeGroupStatOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_by_industrial_park_api_admin_stats_by_industrial_park_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndustrialParkStatOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_admin_api_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAdminOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
